name: deploy_backend

on:
  push:
    branches: [ main ]
    paths: 
    - 'backend/**'

env:
  AZURE_WEBAPP_NAME: GetResumeCounter
  AZURE_WEBAPP_PACKAGE_PATH: 'backend' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '6.0.1' # The .NET SDK version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - names: 'Checkout Github Action'
      uses: actions/checkout@main

    - name: 'Login via azure CLI'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup .NET Core    # Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - names: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run unit test'
      slell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/tests'
        dotnet test

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output'